/**
 * The only module in the codebase that talks to Supabase Storage (CC-02).
 *
 * Everything above it deals in attachment rows and never in buckets, tokens or
 * HTTP. That boundary is what makes the rest of the feature testable: the unit
 * tests mock this module wholesale and never touch the network.
 *
 * See docs/specs/CC-02-file-storage.md.
 */

import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import {
  DOWNLOAD_URL_TTL_SECONDS,
  STORAGE_ENABLED,
  SUPABASE_SERVICE_ROLE_KEY,
  SUPABASE_STORAGE_BUCKET,
  SUPABASE_URL,
  UPLOAD_URL_TTL_SECONDS,
} from "../../config/env.js";

/**
 * Created lazily rather than at import time.
 *
 * On Vercel every cold start pays for module initialization, and a route that
 * never touches storage should not pay to construct a client. It also keeps
 * importing this module free for tests that mock it.
 */
let client: SupabaseClient | null = null;

const getClient = (): SupabaseClient => {
  if (!STORAGE_ENABLED) {
    // Callers are expected to check STORAGE_ENABLED and answer 503 before
    // reaching this. Throwing rather than returning a dud client means a
    // missed check fails loudly in development instead of producing a signed
    // URL that points nowhere.
    throw new Error(
      "File storage is not configured. Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY.",
    );
  }

  if (!client) {
    client = createClient(SUPABASE_URL as string, SUPABASE_SERVICE_ROLE_KEY as string, {
      auth: { persistSession: false, autoRefreshToken: false },
    });
  }
  return client;
};

const bucket = () => getClient().storage.from(SUPABASE_STORAGE_BUCKET);

export const STORAGE_BUCKET = SUPABASE_STORAGE_BUCKET;

export interface SignedUpload {
  /** The URL the browser PUTs the bytes to. */
  uploadUrl: string;
  /** Supabase returns a token alongside the URL; some clients need it. */
  token: string;
  expiresInSeconds: number;
}

/**
 * Issue a short-lived, single-path upload URL.
 *
 * The path is generated by the caller (never by the client) and is scoped to
 * one object, so a leaked URL can overwrite that object and nothing else.
 */
export const createSignedUpload = async (
  storagePath: string,
): Promise<SignedUpload> => {
  const { data, error } = await bucket().createSignedUploadUrl(storagePath);

  if (error || !data) {
    throw new Error(
      `Failed to sign upload for ${storagePath}: ${error?.message ?? "no data"}`,
    );
  }

  return {
    uploadUrl: data.signedUrl,
    token: data.token,
    expiresInSeconds: UPLOAD_URL_TTL_SECONDS,
  };
};

/**
 * Issue a short-lived download URL.
 *
 * `download` sets Content-Disposition: attachment on Supabase's side. That
 * matters for more than convenience — it stops a crafted file being rendered
 * inline in the browser, which is the cheap half of not having a virus
 * scanner.
 */
export const createSignedDownload = async (
  storagePath: string,
  originalName?: string,
): Promise<{ url: string; expiresInSeconds: number }> => {
  const { data, error } = await bucket().createSignedUrl(
    storagePath,
    DOWNLOAD_URL_TTL_SECONDS,
    originalName ? { download: originalName } : undefined,
  );

  if (error || !data) {
    throw new Error(
      `Failed to sign download for ${storagePath}: ${error?.message ?? "no data"}`,
    );
  }

  return { url: data.signedUrl, expiresInSeconds: DOWNLOAD_URL_TTL_SECONDS };
};

export interface ObjectHead {
  exists: boolean;
  sizeBytes: number;
  mimeType: string | null;
}

/**
 * Look up an object's real size and type.
 *
 * This is the check that actually enforces the size cap: the value the client
 * sent at signing time is a claim, and a client that wants to bypass the cap
 * simply lies. Supabase has no HEAD primitive, so this lists the containing
 * prefix and filters — fine at our fan-out, where a prefix holds one file.
 */
export const headObject = async (storagePath: string): Promise<ObjectHead> => {
  const lastSlash = storagePath.lastIndexOf("/");
  const prefix = lastSlash === -1 ? "" : storagePath.slice(0, lastSlash);
  const name = storagePath.slice(lastSlash + 1);

  const { data, error } = await bucket().list(prefix, {
    limit: 100,
    search: name,
  });

  if (error) {
    throw new Error(`Failed to stat ${storagePath}: ${error.message}`);
  }

  const match = data?.find((entry) => entry.name === name);

  if (!match) {
    return { exists: false, sizeBytes: 0, mimeType: null };
  }

  return {
    exists: true,
    sizeBytes: Number(match.metadata?.size ?? 0),
    mimeType: (match.metadata?.mimetype as string | undefined) ?? null,
  };
};

/**
 * Remove objects. Tolerant by design: the sweep calls this for things that may
 * already be gone, and "already deleted" is the outcome it wanted anyway.
 */
export const deleteObjects = async (storagePaths: string[]): Promise<void> => {
  if (storagePaths.length === 0) return;

  const { error } = await bucket().remove(storagePaths);

  if (error) {
    throw new Error(
      `Failed to delete ${storagePaths.length} object(s): ${error.message}`,
    );
  }
};

/**
 * Pull an object's bytes into memory (CC-50).
 *
 * The only read path that brings a file through the server rather than handing
 * the browser a signed URL, and it exists for one reason: the vision model
 * needs the image inlined in a request we control. Sending it a signed URL
 * instead would be cheaper on bandwidth but would hand a third party a live
 * credential to a private bucket.
 *
 * Callers must bound what they ask for — `VISION_MAX_IMAGE_BYTES` is checked
 * against the recorded size *before* this is called, so a 5 MB ceiling is
 * never exceeded by a lambda that has ~1 GB of memory and a 4.5 MB body limit.
 */
export const downloadObject = async (storagePath: string): Promise<Buffer> => {
  const { data, error } = await bucket().download(storagePath);

  if (error || !data) {
    throw new Error(
      `Failed to download ${storagePath}: ${error?.message ?? "no data"}`,
    );
  }

  return Buffer.from(await data.arrayBuffer());
};
